### PR TITLE
Add uk_ua translation

### PR DESCRIPTION
**Pull request by masik16u**
A few things that were not easy to translate so they could be not totally correct:

- "Mulberry": in Ukrainian it sounds similar to silk ("Mulberry Planks" would sound like "Silk Planks") so I chose one of the folk names of this tree.
- On line 134 there is "item.verdance.mulberry": "Mulberry" I am not sure what that means so I put the tree name there
- "Grilled": there is no appropriate word for this adjective so I used "Baked" instead
- "Pitch": there is no appropriate word to say as one word so I used "Octave" instead

Everything else should be fine 
P.S. The order of translation keys is very uncomfortable to work with, if you want I can help to organize it

### CODE REVIEW

**Comment by ExDrill** [comment]
I'm going to hold on merging this, we're in the middle of working on the next update for Verdance

**Comment by ExDrill** [comment]
> I'm going to hold on merging this, we're in the middle of working on the next update for Verdance

Regarding this, would you be willing to complete this PR to match the English language files once the update is complete? If so, I'll send another reply that the update's language files are ready to be translated.

**Comment by masik16u** [comment]
> > I'm going to hold on merging this, we're in the middle of working on the next update for Verdance
> 
> Regarding this, would you be willing to complete this PR to match the English language files once the update is complete? If so, I'll send another reply that the update's language files are ready to be translated.

Sure, I will wait until you update the mod and then I will update the file

**Comment by ExDrill** [comment]
We've finished all content that require translations! Thanks in advance!

**Comment by masik16u** [comment]
> We've finished all content that require translations! Thanks in advance!

I think that's all

**Comment by ExDrill** [comment]
Thanks!

**Pull request merged**
